services:
  postgres:
    image: tensorzero/postgres:14
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "cron.database_name=test"]
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      start_period: 30s
      start_interval: 1s
      timeout: 1s
