services:
  postgres:
    image: tensorzero/postgres-dev:14-trixie-slim
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=test
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      start_period: 30s
      start_interval: 1s
      timeout: 1s
